#!/bin/sh

# clear the port list file
#
# Usage: cplf
#
# globals expected in ${HOME}/.ports.conf with sample values
# listf='ports.txt' # ports list file; relative to $HOME if no leading '/'

. "$HOME/.ports.conf"

[ -n "${listf##/*}" ] && listf="${HOME}/$listf"
: > "$listf"
