#!/bin/sh

# update a ports tree
#
# Usage: pull
#
#
# globals expected in ${HOME}/.ports.conf with sample values
# No leading '/' on directory names means they are relative to $HOME
# portsd='/usr/ports'           # ports directory

. "$HOME/.ports.conf"

usage () {
  cat <<EOF 1>&2
Usage: ${0##*/} [-m gsr|gpr|pdr|svn]
EOF
}

# pull changes
pull() {

  local ret=-1

  printf "* git -C ${portsd} pull freebsd main --ff-only\\n"
  git -C ${portsd} pull freebsd main --ff-only
  
}

pull
